version: "3.9"
services:
  db:
    image: postgres:16
    container_name: sxpr_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sxpr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sxpr_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: sxpr_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      racket_runner:
        condition: service_healthy
    env_file:
      - .env
    environment:
      RACKET_RUNNER_URL: http://racket_runner:8080
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  racket_runner:
    build:
      context: ./racket-runner
    container_name: sxpr_racket_runner
    restart: unless-stopped
    ports:
      - "8080:8080"
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  web:
    build:
      context: ./s-expression-vite
      dockerfile: Dockerfile.prod
    image: sxpr-frontend:latest
    container_name: sxpr_web
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    profiles: ["production"]

  vite-dev:
    build:
      context: ./s-expression-vite
      dockerfile: Dockerfile.dev
    container_name: sxpr_vite_dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./s-expression-vite:/app:cached
      - /app/node_modules
    environment:
      - VITE_API_BASE=http://localhost:8000
    profiles: ["development"]

volumes:
  pgdata: